### ISSUE TITLE
Interest Timer Not Functional

### ISSUE THREAD

**Issue by graywolf336** [Dablakbandit/Bank#9]
Whenever I enable the interest timer and set it to 24 hours, `62400`, and reload the plugin `/bank reload` it says `[18:10:57 INFO]: [Bank] Money interest starting, next in 0 seconds` and then when I do `/bank time` it shows the following:

![image](https://user-images.githubusercontent.com/850391/54569589-6d167600-49a9-11e9-8bf0-6a87202186fa.png)

```
Money:
  Enabled: true
  Max: 1000000
  Cheque_Enabled: false
  Full_Dollars: false
  Deposit_Full: false
  Default: 0.0
  Send_Other: false
  Interest:
    Enable: true
    Main: false
    Message_Enabled: false
    Percent_Gained_Online: 0.05
    Percent_Gained_Offline: 0.03
    Timer: 62400
    Next: 0
    Max: 1.7976931348623157E308
    Max_Offline: 1.7976931348623157E308
    Account_Minimum: 0.0
  No_Format: false
  Top:
    Blacklist:
    - <uuid>
```

Is there anything else I need to do?
